// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjuvfssdksdzdntedwqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqdXZmc3Nka3NkemRudGVkd3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjU2NzMsImV4cCI6MjA2ODQ0MTY3M30.QPnFXRrOtnvsw7Yk-S9FgiDZyV11hbMMqJ_-2C6kz_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});